version: '3.8'

services:

  infinitude:
    image: nebulous/infinitude:latest@sha256:313d0cdd46a404861cfe9e880b5b5c2610eb39207f6fb299fc9ee9a112e49403
    ports:
      # The thermostat has trouble connecting through the proxy, on both 80 and 443.
      # Exposing this port so it can be routed directly.
      - 3000:3000
    environment:
      # cookie signature for perl web framework (mojolicious)
      - APP_SECRET=subjectivizes
      # forward requests every n seconds (default 17 minutes)
      - PASS_REQS=300
      # more logging
      - MODE=Development
    volumes:
      - infinitude-data:/infinitude/state
    deploy:
      placement:
        constraints:
          - node.platform.arch == aarch64
      labels:
        - traefik.enable=true
        - traefik.http.routers.infinitude.rule=Host(`infinitude.lab.omglolwtfbbq.com`)
        - traefik.http.routers.infinitude.entrypoints=web-secure
        - traefik.http.routers.infinitude.tls.certResolver=primary
        - traefik.http.routers.infinitude.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.infinitude.loadbalancer.server.port=3000

  infinitude-prometheus:
    image: ghcr.io/jeremyhayes/infinitude-prometheus:v0.1.46
    environment:
      - INFINITUDE_BASE_URL=http://infinitude:3000
    deploy:
      placement:
        constraints:
          - node.platform.arch == aarch64
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=8080

volumes:
  infinitude-data:
#    driver: local
#    driver_opts:
#      type: nfs4
#      o: addr=192.168.42.11,rw
#      device: ":/mnt/hdd/share/apps/infinitude"
