version: '3.8'

services:

  whoami:
    image: traefik/whoami:v1.6.1
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.lab.omglolwtfbbq.com`)
      - traefik.http.routers.whoami.entrypoints=web
    networks:
      - pi-cluster

networks:
  pi-cluster:
    external: true
