version: '3.8'

services:

  whoami:
    image: traefik/whoami:v1.8.6
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoami.rule=Host(`whoami.lab.omglolwtfbbq.com`)
        - traefik.http.routers.whoami.entrypoints=web-secure
        - traefik.http.routers.whoami.tls.certResolver=primary
        - traefik.http.routers.whoami.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.whoami.loadbalancer.server.port=80
