version: '3.8'

services:

  loki:
    image: grafana/loki:2.6.1
    command: "-config.file=/etc/loki/config.yml"
    volumes:
      - loki-data:/data/loki
    configs:
      - source: loki-yml
        target: /etc/loki/config.yml
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86_64

  promtail:
    image: grafana/promtail:2.6.1
    command: "-config.file=/etc/promtail/config.yml"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    configs:
      - source: promtail-yml
        target: /etc/promtail/config.yml
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86_64

configs:
  loki-yml:
    file: ./loki.yml
  promtail-yml:
    file: ./promtail.yml

volumes:
  loki-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/apps/loki"
