services:

  paperless-db-init:
    image: ghcr.io/jeremyhayes/postgres-init:v0.0.3
    secrets:
      - lab_postgres-su-password
      - paperless-postgres-password
    environment:
      PG_HOST: postgres
      PG_PASSWORD_FILE: /run/secrets/lab_postgres-su-password
      DB_USERNAME: paperless
      DB_PASSWORD_FILE: /run/secrets/paperless-postgres-password
    deploy:
      restart_policy:
        condition: none

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.17.1
    secrets:
      - paperless-postgres-password
      - paperless-secret-key
    volumes:
      - paperless-data:/usr/src/paperless/data
      - paperless-media:/usr/src/paperless/media
      - paperless-export:/usr/src/paperless/export
      - paperless-import:/usr/src/paperless/consume
    environment:
      # Database
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS_FILE: /run/secrets/paperless-postgres-password
      # Redis
      PAPERLESS_REDIS: redis://valkey:6379/3
      PAPERLESS_REDIS_PREFIX: paperless
      # Office parsing
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_ENDPOINT: http://paperless-tika:9998
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless-gotenberg:3000

      # Cookies
      PAPERLESS_SECRET_KEY_FILE: /run/secrets/paperless-secret-key

      # Proxy
      PAPERLESS_URL: https://paperless.lab.omglolwtfbbq.com

      # SSO
      PAPERLESS_DISABLE_REGULAR_LOGIN: 'True'
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      # This has to be configured manually after app setup. There is no available automation.
      # PAPERLESS_SOCIALACCOUNT_PROVIDERS:
    deploy:
      placement:
        constraints:
          - node.platform.arch == x86_64
      labels:
#        - prometheus.swarm.enable=true
#        - prometheus.swarm.port=8000
        - traefik.enable=true
        - traefik.http.routers.paperless.rule=Host(`paperless.lab.omglolwtfbbq.com`)
        - traefik.http.routers.paperless.entrypoints=web-secure
        - traefik.http.routers.paperless.tls.certResolver=primary
        - traefik.http.routers.paperless.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.paperless.loadbalancer.server.port=8000

  paperless-tika:
    image: docker.io/apache/tika:3.2.1.0

  paperless-gotenberg:
    image: docker.io/gotenberg/gotenberg:8.21.1
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

secrets:
  lab_postgres-su-password:
    external: true
  paperless-secret-key:
    file: ./.secret.paperless-secret-key
  paperless-postgres-password:
    file: ./.secret.paperless-postgres-password

volumes:
  paperless-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/apps/paperless/data"
  paperless-media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/mnt/nas/documents"
  paperless-import:
    # TODO
  paperless-export:
    # TODO
