version: "3.8"

networks:
  immich:
    driver: overlay
  web-proxy:
    driver: overlay
    external: true

volumes:
  library:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/nas/images
  model-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/stacks/immich/immich/model-cache
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/stacks/immich/postgres/data

secrets:
  authentik_immich-client-id:
    external: true
  authentik_immich-client-secret:
    external: true
  postgres-password:
    file: ./.secret.postgres-password

services:

  server: &immich-server
    image: ghcr.io/immich-app/immich-server:v2.4.1
    command: |
      "
      cp /etc/immich.yaml.tpl /etc/immich.yaml
      sed -i 's|$$OAUTH_CLIENT_ID|'$$(cat /run/secrets/authentik_immich-client-id)'|g' /etc/immich.yaml
      sed -i 's|$$OAUTH_CLIENT_SECRET|'$$(cat /run/secrets/authentik_immich-client-secret)'|g' /etc/immich.yaml

      start.sh
      "
    networks:
      - immich
      - web-proxy
    secrets:
      - authentik_immich-client-id
      - authentik_immich-client-secret
      - postgres-password
    environment: &immich-environment
      DB_HOSTNAME: postgres
      DB_DATABASE_NAME: immich
      DB_USERNAME: immich
      DB_PASSWORD_FILE: /run/secrets/postgres-password
      IMMICH_CONFIG_FILE: /etc/immich.yaml
      IMMICH_TELEMETRY_INCLUDE: all
      IMMICH_WORKERS_INCLUDE: api
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - library:/data
      - ./immich/config.yaml:/etc/immich.yaml.tpl:ro
    deploy: &immich-deploy
      placement:
        constraints:
          - node.role == manager # for mapped data volume
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=8081
        - traefik.enable=true
        - traefik.http.routers.immich.rule=Host(`immich.lab.omglolwtfbbq.com`)
        - traefik.http.routers.immich.entrypoints=web-secure
        - traefik.http.routers.immich.tls.certResolver=primary
        - traefik.http.routers.immich.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.immich.loadbalancer.server.port=2283

  microservices:
    <<: *immich-server
    networks:
      - immich
    environment:
      <<: *immich-environment
      IMMICH_WORKERS_INCLUDE: microservices
    deploy:
      <<: *immich-deploy
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=8082

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.4.1
    networks:
      - immich
    volumes:
      - model-cache:/cache
    deploy:
      placement:
        constraints:
          - node.role == manager # for mapped data volume

  postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    networks:
      - immich
    secrets:
      - postgres-password
    environment:
      POSTGRES_DB: immich
      POSTGRES_USER: immich
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_INITDB_ARGS: "--data-checksums"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    deploy:
      placement:
        constraints:
          - node.role == manager # for mapped data volume

  redis:
    image: valkey/valkey:9.0.1-alpine
    networks:
      - immich
