version: '3.8'

services:

  prometheus:
    image: prom/prometheus:v2.33.3
    volumes:
      - prometheus-data:/prometheus
    configs:
      - source: prometheus-yml
        target: /etc/prometheus/prometheus.yml
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=9090
        - traefik.enable=true
        - traefik.http.routers.prometheus.rule=Host(`prometheus.lab.omglolwtfbbq.com`)
        - traefik.http.routers.prometheus.entrypoints=web-secure
        - traefik.http.routers.prometheus.tls.certResolver=primary
        - traefik.http.routers.prometheus.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.prometheus.loadbalancer.server.port=9090

configs:
  prometheus-yml:
    file: ./prometheus.yml

volumes:
  prometheus-data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.42.11,rw
      device: ":/mnt/hdd/share/apps/prometheus"
