version: '3.8'

services:

  prometheus:
    image: prom/prometheus:v2.28.1
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`prometheus.lab.omglolwtfbbq.com`)
      - traefik.http.routers.prometheus.entrypoints=web

volumes:
  prometheus-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.42.11,nolock,soft,rw
      device: ":/mnt/hdd/share/apps/prometheus"
