global:
  # every 15s by default
  scrape_interval: 15s

# scrape jobs use docker-compose service names as hostname
scrape_configs:

  # monitor prometheus itself
  - job_name: prometheus
    static_configs:
      - targets: [ 'prometheus:9090' ]

  # monitor grafana
  - job_name: grafana
    static_configs:
      - targets: [ 'grafana:3000' ]

  # traefik
  - job_name: traefik
    static_configs:
      - targets: [ 'traefik:8080' ]

  # monitor cable modem
  - job_name: motorola-mb8600
    scrape_interval: 1m
    scrape_timeout: 30s
    static_configs:
      - targets: [ 'mb8600-exporter:3000' ]

  # unifi controller
  - job_name: unifi-controller
    static_configs:
      - targets: [ 'unifi-poller:9130' ]

  # node_exporter
  - job_name: node
    dns_sd_configs:
      - names:
          - 'tasks.node_exporter'
        type: 'A'
        port: 9100

  # cadvisor
  - job_name: cadvisor
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080

  # swarm nodes
  - job_name: docker
    dockerswarm_sd_configs:
      - host: tcp://172.17.0.1:2375
        role: nodes
    relabel_configs:
      # scrape docker metrics on 9323
      - source_labels: [ __meta_dockerswarm_node_address ]
        target_label: __address__
        replacement: $1:9323

  # swarm tasks
  - job_name: tasks
    dockerswarm_sd_configs:
      - host: tcp://172.17.0.1:2375
        role: tasks
    relabel_configs:
      # Only keep containers that should be running.
      - source_labels: [ __meta_dockerswarm_task_desired_state ]
        regex: running
        action: keep
      # capture the service itself as the "job" (override this single 'tasks' job)
      - source_labels: [ __meta_dockerswarm_service_name ]
        target_label: job
        replacement: $1
      # capture the hostname of the running node
      - source_labels: [ __meta_dockerswarm_node_hostname ]
        target_label: node
        replacement: $1
      # Only keep containers that have a `prometheus-job` label.
      # - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
      #   regex: .+
      #   action: keep
      # Use the task labels that are prefixed by `prometheus-`.
      - regex: __meta_dockerswarm_service_label_prometheus_(.+)
        action: labelmap
        replacement: $1
