version: '3.8'

services:

  pihole:
    image: pihole/pihole:2022.02
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8090:80
    environment:
      - TZ=America/New_York
      - WEBPASSWORD_FILE=/run/secrets/pihole-web-password
      # This must be set in /etc/pihole/pihole-FTL.conf once created.
      # - RATE_LIMIT=0/0
    secrets:
      - pihole-web-password
    volumes:
      - pihole-data:/etc/pihole
      - pihole-dnsmasq:/etc/dnsmasq.d
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    deploy:
      placement:
        constraints:
          # run pihole on manager until/unless figure out how to put it behind proxy
          - node.role == manager
      labels:
#        - traefik.enable=true
        - traefik.http.routers.pihole.rule=Host(`pihole.lab.omglolwtfbbq.com`)
        - traefik.http.routers.pihole.entrypoints=web-secure
        - traefik.http.routers.pihole.tls.certResolver=primary
        - traefik.http.routers.pihole.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.pihole.loadbalancer.server.port=80
        - traefik.tcp.routers.pihole-tcp.rule=HostSNI(`*`)
        - traefik.tcp.routers.pihole-tcp.entrypoints=dns-tcp
        - traefik.tcp.routers.pihole-tcp.service=pihole-tcp
        - traefik.tcp.routers.pihole-tcp.tls.certResolver=primary
        - traefik.tcp.routers.pihole-tcp.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.tcp.services.pihole-tcp.loadbalancer.server.port=53
        - traefik.udp.routers.pihole-udp.entrypoints=dns-udp
        - traefik.udp.routers.pihole-udp.service=pihole-udp
        - traefik.udp.services.pihole-udp.loadbalancer.server.port=53
#        - traefik.udp.services.pihole-udp.loadbalancer.passhostheader=true
#        - traefik.udp.services.pihole-udp.passhostheader=true

  pihole-exporter:
    image: ekofr/pihole-exporter:v0.2.0
    environment:
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PASSWORD=${PIHOLE_PASSWORD}
    deploy:
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=9617

secrets:
  pihole-web-password:
    file: ./.secret.pihole-web-password

volumes:
  pihole-data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.42.11,rw
      device: ":/mnt/hdd/share/apps/pihole/pihole"
  pihole-dnsmasq:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.42.11,rw
      device: ":/mnt/hdd/share/apps/pihole/dnsmasq"
