version: '3.8'

services:

  traefik:
    image: traefik:v2.4.13
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - NAMECHEAP_API_KEY_FILE=/run/secrets/namecheap-api-key
      - NAMECHEAP_API_USER_FILE=/run/secrets/namecheap-api-user
    secrets:
      - namecheap-api-key
      - namecheap-api-user
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    command:
      - --log.level=DEBUG
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
      - --metrics=true
      - --metrics.prometheus=true
      - --certificatesResolvers.primary.acme.email=dev@omglolwtfbbq.com
      - --certificatesResolvers.primary.acme.storage=acme.json
      - --certificatesResolvers.primary.acme.dnsChallenge=true
      - --certificatesResolvers.primary.acme.dnsChallenge.provider=namecheap
      - --certificatesResolvers.primary.acme.dnsChallenge.delayBeforeCheck=0
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=8080
        - traefik.http.routers.api.tls.domains[0].main=lab.omglolwtfbbq.com
        - traefik.http.routers.api.tls.domains[0].sans=*.lab.omglolwtfbbq.com

secrets:
  namecheap-api-key:
    file: ./.secret.namecheap-api-key
  namecheap-api-user:
    file: ./.secret.namecheap-api-user
