version: '3.8'

services:

  traefik:
    image: traefik:v2.5.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - NAMECHEAP_API_KEY_FILE=/run/secrets/namecheap-api-key
      - NAMECHEAP_API_USER_FILE=/run/secrets/namecheap-api-user
    secrets:
      - namecheap-api-key
      - namecheap-api-user
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./route-config:/etc/traefik/config
    configs:
      - source: traefik-yml
        target: /etc/traefik/traefik.yml
      - source: acme-json
        target: /acme.json
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=8080

configs:
  traefik-yml:
    file: ./traefik.yml
  acme-json:
    file: ./acme.json

secrets:
  namecheap-api-key:
    file: ./.secret.namecheap-api-key
  namecheap-api-user:
    file: ./.secret.namecheap-api-user
