version: '3.8'

services:

  traefik:
    image: traefik:v3.0.3
    ports:
#      - 53:53/tcp
#      - 53:53/udp
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - NAMECHEAP_API_KEY_FILE=/run/secrets/namecheap-api-key
      - NAMECHEAP_API_USER_FILE=/run/secrets/namecheap-api-user
    secrets:
      - namecheap-api-key
      - namecheap-api-user
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./route-config:/etc/traefik/config
      - ./acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.platform.arch == x86_64 # only because manager node req
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=8080

secrets:
  namecheap-api-key:
    file: ./.secret.namecheap-api-key
  namecheap-api-user:
    file: ./.secret.namecheap-api-user
