log:
  level: DEBUG

api:
  insecure: true

providers:
  docker:
    swarmMode: true
    exposedByDefault: false
  file:
    directory: /etc/traefik/config
    watch: true

metrics:
  prometheus: {}

entrypoints:
#  dns-tcp:
#    address: :53/tcp
#  dns-udp:
#    address: :53/udp
  web:
    address: :80
  web-secure:
    address: :443

certificatesResolvers:
  primary:
    acme:
      email: dev@jeremyhayes.com
      storage: acme.json
      # uncomment to use Let's Encrypt staging server
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: namecheap
        delayBeforeCheck: 0
