version: '3.8'

services:

  swarm-cronjob:
    image: crazymax/swarm-cronjob:1.10.0
    environment:
      - TZ=America/New_York
      - LOG_LEVEL=info
      - LOG_JSON=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
