version: '3.8'

services:

  grafana:
    image: grafana/grafana:8.3.2
    volumes:
      - grafana-data:/var/lib/grafana
    configs:
      - source: grafana-ini
        target: /etc/grafana/grafana.ini
    deploy:
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=3000
        - traefik.enable=true
        - traefik.http.routers.grafana.rule=Host(`grafana.lab.omglolwtfbbq.com`)
        - traefik.http.routers.grafana.entrypoints=web-secure
        - traefik.http.routers.grafana.tls.certResolver=primary
        - traefik.http.routers.grafana.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.grafana.loadbalancer.server.port=3000

configs:
  grafana-ini:
    file: ./grafana.ini
  
volumes:
  grafana-data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.42.11,rw
      device: ":/mnt/hdd/share/apps/grafana"
