version: '3.8'

services:

  mb8600-exporter:
    image: local/motorola-mb8600-prometheus-exporter
    build: ./motorola-mb8600-prometheus-exporter
    environment:
      - MODEM_BASE_URL=${MODEM_ADDRESS}
      - MODEM_USERNAME=${MODEM_USERNAME}
      - MODEM_PASSWORD=${MODEM_PASSWORD}
      - MODEM_IGNORE_SSL=true

  mb8600-restart:
    image: local/motorola-mb8600-reboot
    build: ./motorola-mb8600-reboot
    command:
      - --url ${MODEM_ADDRESS}
      - --username ${MODEM_USERNAME}
      - --password ${MODEM_PASSWORD}
      - --ignore-ssl
    deploy:
      replicas: 0 # none by default; created when cron hits
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0 5 * * mon
