version: '3.8'

services:

  mb8600-exporter:
    image: ghcr.io/jeremyhayes/motorola-mb8600-prometheus-exporter:v0.6.8
    environment:
      - MODEM_BASE_URL=https://192.168.100.1
      - MODEM_IGNORE_SSL=true
      - MODEM_USERNAME_FILE=/run/secrets/modem-username
      - MODEM_PASSWORD_FILE=/run/secrets/modem-password
    secrets:
      - modem-username
      - modem-password
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86_64
      labels:
        # don't allow prometheus to scrape this; takes too long for global config
        - prometheus.swarm.enable=false
        - prometheus.swarm.port=3000

  mb8600-restart:
    image: ghcr.io/jeremyhayes/motorola-mb8600-reboot:v0.4.6
    environment:
      - MODEM_BASE_URL=https://192.168.100.1
      - MODEM_IGNORE_SSL=true
      - MODEM_USERNAME_FILE=/run/secrets/modem-username
      - MODEM_PASSWORD_FILE=/run/secrets/modem-password
      # - MODEM_REBOOT_DRY_RUN=true
    secrets:
      - modem-username
      - modem-password
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86_64
      restart_policy:
        condition: none
      replicas: 0 # none by default; created when cron hits
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0 5 * * mon

secrets:
  modem-username:
    file: ./.secret.modem-username
  modem-password:
    file: ./.secret.modem-password
