version: '3.8'

services:

  mb8600-exporter:
    image: ghcr.io/jeremyhayes/motorola-mb8600-prometheus-exporter:v0.4.1
    environment:
      - MODEM_BASE_URL=https://192.168.100.1
      - MODEM_IGNORE_SSL=true
      - MODEM_USERNAME_FILE=/run/secrets/modem-username
      - MODEM_PASSWORD_FILE=/run/secrets/modem-password
    secrets:
      - modem-username
      - modem-password
    deploy:
      labels:
        # don't allow prometheus to scrape this; takes too long for global config
        - prometheus.swarm.enable=false

  mb8600-restart:
    image: ghcr.io/jeremyhayes/motorola-mb8600-reboot:v0.1.1
    command:
      - --url
      - ${MODEM_ADDRESS}
      - --username
      - ${MODEM_USERNAME}
      - --password
      - ${MODEM_PASSWORD}
      - --ignore-ssl
    deploy:
      restart_policy:
        condition: none
      replicas: 0 # none by default; created when cron hits
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0 5 * * mon

secrets:
  modem-username:
    file: ./.secret.modem-username
  modem-password:
    file: ./.secret.modem-password
