version: '3.8'

services:

  smokeping:
    image: linuxserver/smokeping:2.7.3
#    volumes:
#      - smokeping-data:/data
    configs:
      - source: smokeping-targets
        target: /config/Targets
    deploy:
      labels:
        - prometheus.swarm.enable=false
        - traefik.enable=true
        - traefik.http.routers.smokeping.rule=Host(`smokeping.lab.omglolwtfbbq.com`)
        - traefik.http.routers.smokeping.entrypoints=web-secure
        - traefik.http.routers.smokeping.tls.certResolver=primary
        - traefik.http.routers.smokeping.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.smokeping.loadbalancer.server.port=80

configs:
  smokeping-targets:
    file: ./config/targets

volumes:
  smokeping-data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.42.11,rw
      device: ":/mnt/hdd/share/apps/smokeping"
