version: '3.8'

services:

  influxdb:
    image: influxdb:2.7.11-alpine
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb-admin-token
      DOCKER_INFLUXDB_INIT_ORG: homelab
      DOCKER_INFLUXDB_INIT_BUCKET: default
    secrets:
      - influxdb-admin-username
      - influxdb-admin-password
      - influxdb-admin-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=8086
        - traefik.enable=true
        - traefik.http.routers.foo.rule=Host(`influxdb.lab.omglolwtfbbq.com`)
        - traefik.http.routers.foo.entrypoints=web-secure
        - traefik.http.routers.foo.tls.certResolver=primary
        - traefik.http.routers.foo.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.foo.loadbalancer.server.port=8086

secrets:
  influxdb-admin-username:
    file: ./.secret.influxdb-admin-username
  influxdb-admin-password:
    file: ./.secret.influxdb-admin-password
  influxdb-admin-token:
    file: ./.secret.influxdb-admin-token

volumes:
  influxdb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/apps/influxdb/data"
  influxdb-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/apps/influxdb/config"
