version: '3.8'

services:

  foo-service:
    image: foo
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`foo.lab.omglolwtfbbq.com`)
      - traefik.http.routers.whoami.entrypoints=web
