version: '3.8'

networks:
  paperless:
    driver: overlay
  web-proxy:
    external: true

secrets:
  authentik_paperless-client-id:
    external: true
  authentik_paperless-client-secret:
    external: true
  paperless-secret-key:
    file: ./.secret.paperless-secret-key
  postgres-password:
    file: ./.secret.postgres-password

volumes:
  paperless-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/stacks/paperless/paperless/data
  paperless-media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/nas/documents/media
  paperless-consume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/nas/documents/consume
  paperless-export:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/nas/documents/export
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/stacks/paperless/postgres/data
  broker-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/stacks/paperless/broker/data

services:

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.0
    networks:
      - paperless
      - web-proxy
    secrets:
      - authentik_paperless-client-id
      - authentik_paperless-client-secret
      - paperless-secret-key
      - postgres-password
    environment:
      # Database
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS_FILE: /run/secrets/postgres-password
      # Broker (Redis/Valkey)
      PAPERLESS_REDIS: redis://broker:6379
      # Office parsing
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      # SSO
      PAPERLESS_DISABLE_REGULAR_LOGIN: 'True'
      PAPERLESS_AUTO_CREATE: 'True'
      PAPERLESS_LOGOUT_REDIRECT_URL: https://auth.lab.omglolwtfbbq.com/application/o/paperless/end-session/
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      # This is written by a custom init script for secrets handling
      # PAPERLESS_SOCIALACCOUNT_PROVIDERS:
      # Misc
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_SECRET_KEY_FILE: /run/secrets/paperless-secret-key
      PAPERLESS_TIME_ZONE: America/New_York
      PAPERLESS_URL: https://paperless.lab.omglolwtfbbq.com
    volumes:
      - paperless-data:/usr/src/paperless/data
      - paperless-media:/usr/src/paperless/media
      - paperless-consume:/usr/src/paperless/consume
      - paperless-export:/usr/src/paperless/export
      - ./scripts:/custom-cont-init.d:ro
    deploy:
      placement:
        constraints:
          - node.role == manager # for mapped data volume
      labels:
        - traefik.enable=true
        - traefik.http.routers.paperless.rule=Host(`paperless.lab.omglolwtfbbq.com`)
        - traefik.http.routers.paperless.entrypoints=web-secure
        - traefik.http.routers.paperless.tls.certResolver=primary
        - traefik.http.routers.paperless.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.paperless.loadbalancer.server.port=8000

  postgres:
    image: postgres:18.1-alpine
    networks:
      - paperless
    secrets:
      - postgres-password
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    deploy:
      placement:
        constraints:
          - node.role == manager # for mapped data volume

  broker:
    image: valkey/valkey:9.0.0-alpine
    networks:
      - paperless
    volumes:
      - broker-data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager # for mapped data volume

  tika:
    image: docker.io/apache/tika:3.2.3.0
    networks:
      - paperless

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.24.0
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - paperless
