{
 "title": "Airgradient",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "chip_id",
    "label": "Device",
    "query": {
     "query": "label_values(airgradient_rco2, chip_id)\t"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(airgradient_atmp{chip_id=\"$chip_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature (C)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(airgradient_atmp{chip_id=\"$chip_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Home Temp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "targets": [
    { "expr": "infinitude_status_rt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temp",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(airgradient_atmp{chip_id=\"$chip_id\"}) * 9/5 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature (F)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "avg(airgradient_atmp{chip_id=\"$chip_id\"}) * 9/5 + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outdoor Temp",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "infinitude_status_oat", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(airgradient_rhum{chip_id=\"$chip_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(airgradient_rhum{chip_id=\"$chip_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Home Humidity",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "infinitude_status_rh", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CO2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(airgradient_rco2{chip_id=\"$chip_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "avg(airgradient_rco2{chip_id=\"$chip_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO2 Change",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "rate(airgradient_rco2{chip_id=\"$chip_id\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PM 2.5",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(airgradient_pm02{chip_id=\"$chip_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PM 2.5",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "expr": "avg(airgradient_pm02{chip_id=\"$chip_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PM 2.5 Change",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "avg by(chip_id) (rate(airgradient_pm02{chip_id=\"$chip_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}