{
 "title": "Infinitude",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "period_id", "label": "Period", "query": "day1" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Indoor Air Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "avg by (zone_id) (infinitude_status_rt)"
    }
   ]
  },
  {
   "title": "Indoor Relative Humidity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (zone_id) (infinitude_status_rh)"
    }
   ]
  },
  {
   "title": "Filter Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "infinitude_status_filtrlvl" }
   ]
  },
  {
   "title": "Outside Air Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "avg by (zone_id) (infinitude_status_oat)"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Continuous Fan Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "avg by (zone_id) (infinitude_energy_usage_fan{period_id=\"$period_id\"})",
     "legendFormat": "{{period_id}}"
    }
   ]
  },
  {
   "title": "Cooling Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "avg by (zone_id) (infinitude_energy_usage_cooling{period_id=\"$period_id\"})",
     "legendFormat": "{{period_id}}"
    }
   ]
  },
  {
   "title": "Gas Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "thm" } },
   "targets": [
    {
     "expr": "avg by (zone_id) (infinitude_energy_usage_gas{period_id=\"$period_id\"})",
     "legendFormat": "{{period_id}}"
    }
   ]
  },
  {
   "title": "Continuous Fan YoY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "avg by (zone_id) (infinitude_energy_usage_fan{period_id=\"year1\"})",
     "legendFormat": "YTD"
    },
    {
     "expr": "avg by (zone_id) (infinitude_energy_usage_fan{period_id=\"year2\"})",
     "legendFormat": "Last Year"
    }
   ]
  },
  {
   "title": "Cooling Usage YoY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "avg by (zone_id) (infinitude_energy_usage_cooling{period_id=\"year1\"})",
     "legendFormat": "YTD"
    },
    {
     "expr": "avg by (zone_id) (infinitude_energy_usage_cooling{period_id=\"year2\"})",
     "legendFormat": "Last Year"
    }
   ]
  },
  {
   "title": "Gas Usage YoY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "thm" } },
   "targets": [
    {
     "expr": "avg by (zone_id) (infinitude_energy_usage_gas{period_id=\"year1\"}/100)",
     "legendFormat": "YTD"
    },
    {
     "expr": "avg by (zone_id) (infinitude_energy_usage_gas{period_id=\"year2\"}/100)",
     "legendFormat": "Last Year"
    }
   ]
  }
 ]
}