{
 "title": "Jellyfin",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "jack-the-ripper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{node=\"jack-the-ripper\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',node=\"jack-the-ripper\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{node=\"jack-the-ripper\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode!='idle',node=\"jack-the-ripper\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (node_hwmon_temp_celsius{node=\"jack-the-ripper\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{node=\"jack-the-ripper\"} - node_boot_time_seconds{node=\"jack-the-ripper\"}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{node=\"jack-the-ripper\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=\"jack-the-ripper\"}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{node=\"jack-the-ripper\",mountpoint=\"/\"} * 100) / node_filesystem_size_bytes{node=\"jack-the-ripper\",mountpoint=\"/\"})",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{node=\"jack-the-ripper\",mountpoint=\"/home\"} * 100) / node_filesystem_size_bytes{node=\"jack-the-ripper\",mountpoint=\"/home\"})",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{node=\"jack-the-ripper\",mountpoint=\"/mnt/nas/media\"} * 100) / node_filesystem_size_bytes{node=\"jack-the-ripper\",mountpoint=\"/mnt/nas/media\"})",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes{node=\"jack-the-ripper\"} - node_memory_SwapFree_bytes{node=\"jack-the-ripper\"}) / (node_memory_SwapTotal_bytes{node=\"jack-the-ripper\"} )) * 100",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Total - /",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{node=\"jack-the-ripper\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{node=\"jack-the-ripper\"} * 100) / node_memory_MemTotal_bytes{node=\"jack-the-ripper\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{node=\"jack-the-ripper\"} * 100) / node_memory_MemTotal_bytes{node=\"jack-the-ripper\"})"
    }
   ]
  },
  {
   "title": "Total - /home",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{node=\"jack-the-ripper\",mountpoint=\"/home\"}"
    }
   ]
  },
  {
   "title": "Total - /mnt/nas/media",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{node=\"jack-the-ripper\",mountpoint=\"/mnt/nas/media\"}"
    }
   ]
  },
  {
   "title": "Total - swap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{node=\"jack-the-ripper\"}"
    }
   ]
  },
  { "title": "ARM - Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"arm-rippers\"}[5m])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{container_label_com_docker_compose_service=\"arm-rippers\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_receive_bytes_total{container_label_com_docker_compose_service=\"arm-rippers\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_transmit_bytes_total{container_label_com_docker_compose_service=\"arm-rippers\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{container_label_com_docker_compose_service=\"arm-rippers\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Jellyfin - Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"lab_jellyfin\"}[5m])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{container_label_com_docker_swarm_service_name=\"lab_jellyfin\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=\"lab_jellyfin\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=\"lab_jellyfin\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{container_label_com_docker_swarm_service_name=\"lab_jellyfin\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Jellyfin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "dotnet_total_memory_bytes{job=\"jellyfin\"}",
       "legendFormat": "Dotnet total memory"
      },
      {
       "expr": "process_private_memory_bytes{job=\"jellyfin\"}",
       "legendFormat": "Process private memory"
      },
      {
       "expr": "process_working_set_bytes{job=\"jellyfin\"}",
       "legendFormat": "Process working set"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 48 },
     "targets": [
      {
       "expr": "rate(http_requests_received_total{job=\"jellyfin\"}[$__rate_interval])",
       "legendFormat": "{{method}} {{controller}} {{action}} {{code}}"
      }
     ]
    },
    {
     "title": "Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "rate(dotnet_exceptions_total{job=\"jellyfin\"}[$__rate_interval])",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}