{
 "title": "Network Health",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Download Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unpoller_device_speedtest_download)"
    }
   ]
  },
  {
   "title": "Downstream Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(moto_downstream_channel_power_dbmv)"
    }
   ]
  },
  {
   "title": "Downstream SNR (db)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "avg by (channelId, modulation) (moto_downstream_channel_signal_noise_ratio)",
     "legendFormat": "{{channelId}} - {{modulation}}"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unpoller_device_speedtest_upload)"
    }
   ]
  },
  {
   "title": "Upstream Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dBmV" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(moto_upstream_channel_power_dbmv)"
    }
   ]
  },
  {
   "title": "Node Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(node_hwmon_temp_celsius)" }
   ]
  },
  {
   "title": "DPI",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by (category, application) (increase(unpoller_client_dpi_receive_bytes{application!~\"TOTAL\"}[$__range])+increase(unpoller_client_dpi_transmit_bytes{application!~\"TOTAL\"}[$__range]))",
     "legendFormat": "{{application}} ({{category}})"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Device Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unpoller_device_temperature_celsius{temp_type=\"cpu\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pihole_domains_being_blocked)",
     "legendFormat": "Blocked Domains"
    },
    { "expr": "sum(pihole_dns_queries_today)", "legendFormat": "Queries" },
    { "expr": "sum(pihole_ads_blocked_today)", "legendFormat": "Queries Blocked" },
    {
     "expr": "(sum(pihole_ads_blocked_today) / sum(pihole_dns_queries_today)) * 100",
     "legendFormat": "Queries Blocked %"
    }
   ]
  },
  {
   "title": "Top Permitted Domains",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "topk(10, pihole_top_queries)", "legendFormat": "{{domain}}" }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "targets": [
    { "expr": "topk(10, pihole_top_ads)", "legendFormat": "{{domain}}" }
   ]
  }
 ]
}