{
 "title": "Octoprint",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Nozzle Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octoprint_temperatures_actual{identifier=\"T0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_printer_state_info", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_print_progress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Estimate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_print_time_est", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "X Travel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_x_travel_print", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Progress",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_print_progress", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "Y Travel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_y_travel_print", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Elapsed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_print_time_elapsed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bed Temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octoprint_temperatures_actual{identifier=\"B\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Z Travel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "octoprint_z_travel_print", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octoprint_print_time_left_estimate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filament Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "octoprint_extrusion_print / 37233160.59",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "targets": [
    { "expr": "octoprint_printer_state_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Started",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "octoprint_started_prints_total" }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "octoprint_done_prints_total" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 15 },
   "targets": [
    { "expr": "octoprint_print_time_est", "legendFormat": "__auto" },
    { "expr": "octoprint_extrusion_print", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cancelled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "octoprint_cancelled_prints_total"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "octoprint_failed_prints_total" }
   ]
  }
 ]
}