{
 "title": "Pi Hole",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": {
     "query": "label_values(pihole_status,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_status", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Total Queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pihole_dns_queries_today{hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pihole_ads_blocked_today{hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage Blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pihole_ads_blocked_today{hostname=~\"$hostname\"}) / sum(pihole_dns_queries_today{hostname=~\"$hostname\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Domains on Adlists",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pihole_domains_being_blocked{hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(idelta(pihole_ads_blocked_today{hostname=~\"$hostname\"}[$__interval]))",
     "legendFormat": "Blocked"
    },
    {
     "expr": "sum(idelta(pihole_queries_forwarded{hostname=~\"$hostname\"}[$__interval]))",
     "legendFormat": "Permitted"
    }
   ]
  },
  {
   "title": "Client Activity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(idelta(pihole_top_sources{hostname=~\"$hostname\"}[$__interval])) by (source) > 0",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Query Types",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(type) (pihole_querytypes{hostname=~\"$hostname\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Upstream Servers",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(destination) (pihole_forward_destinations{hostname=~\"$hostname\"})",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Top Permitted Domains",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by(domain) (pihole_top_queries{hostname=~\"$hostname\"})))",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Top Blocked Domains",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by(domain) (pihole_top_ads{hostname=~\"$hostname\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Clients",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by(source) (pihole_top_sources{hostname=~\"$hostname\"})))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}