{
 "title": "Temperature",
 "time": { "from": "now-14d", "to": "now" },
 "panels": [
  {
   "title": "Indoor Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "infinitude_status_rt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Outdoor Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "infinitude_status_oat", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Unifi UDM Pro",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "unifipoller_device_temperature_celsius",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Orthanc CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{node=\"orthanc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "lab-pi-01 CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{node=\"lab-pi-01\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}