version: '3.8'

services:

  infinitude:
    image: nebulous/infinitude:latest@sha256:ed57669501601ac35819cdf7734c6f3c373ae957f880829802aca48e44a1a5b6
    # run c_rehash to calculate certificate checksums
    # something with ssl and libseccomp in the host OS
    entrypoint: "/bin/sh -c 'c_rehash && /infinitude/entrypoint.sh' "
    ports:
      - 3000:3000
    environment:
      # cookie signature for perl web framework (mojolicious)
      - APP_SECRET=subjectivizes
      # forward requests every n seconds (default 17 minutes)
      - PASS_REQS=300
      # more logging
      - MODE=Development
    volumes:
      - infinitude-data:/infinitude/state

volumes:
  infinitude-data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=192.168.42.11,rw
      device: ":/mnt/hdd/share/apps/infinitude"
