version: '3.8'

services:

  infinitude:
    image: nebulous/infinitude:latest@sha256:3069c0851ce9c8d96648b13a648abdec8dd11db8071b7b3b78d1732b1e5ae199
    ports:
      - 3000:3000
    environment:
      # cookie signature for perl web framework (mojolicious)
      - APP_SECRET=subjectivizes
      # forward requests every n seconds (default 17 minutes)
      - PASS_REQS=300
      # more logging
      - MODE=Development
    volumes:
      - infinitude-data:/infinitude/state
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86_64

  infinitude-prometheus:
    image: ghcr.io/jeremyhayes/infinitude-prometheus:v0.1.4
    environment:
      - INFINITUDE_BASE_URL=http://infinitude:3000
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86_64
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=8080

volumes:
  infinitude-data:
#    driver: local
#    driver_opts:
#      type: nfs4
#      o: addr=192.168.42.11,rw
#      device: ":/mnt/hdd/share/apps/infinitude"
