http:

  routers:
    home-assistant:
      entryPoints:
        - web-secure
      rule: Host(`home-assistant.lab.omglolwtfbbq.com`)
      service: home-assistant
      tls:
        certResolver: primary
        domains:
          - main: '*.lab.omglolwtfbbq.com'

  services:
    home-assistant:
      loadBalancer:
        servers:
          - url: http://192.168.50.100:8123/
        serversTransport: home-assistant-transport

  serversTransports:
    home-assistant-transport:
      insecureSkipVerify: true
