http:

  middlewares:
    pihole-admin-prefix:
      # Redirect naked root to /admin for dashboard
      # Only for naked root; /api is a root path
      replacePathRegex:
        regex: "^/$"
        replacement: "/admin"

  routers:
    pihole1-dashboard:
      entryPoints:
        - web-secure
      middlewares:
        - proxy-auth@swarm
        - pihole-admin-prefix@file
      rule: Host(`pihole1.lab.omglolwtfbbq.com`)
      service: pihole1-dashboard
      tls:
        certResolver: primary
        domains:
          - main: '*.lab.omglolwtfbbq.com'

    pihole2-dashboard:
      entryPoints:
        - web-secure
      middlewares:
        - proxy-auth@swarm
        - pihole-admin-prefix@file
      rule: Host(`pihole2.lab.omglolwtfbbq.com`)
      service: pihole2-dashboard
      tls:
        certResolver: primary
        domains:
          - main: '*.lab.omglolwtfbbq.com'

    pihole3-dashboard:
      entryPoints:
        - web-secure
      middlewares:
        - proxy-auth@swarm
        - pihole-admin-prefix@file
      rule: Host(`pihole3.lab.omglolwtfbbq.com`)
      service: pihole3-dashboard
      tls:
        certResolver: primary
        domains:
          - main: '*.lab.omglolwtfbbq.com'

  services:
    pihole1-dashboard:
      loadBalancer:
        servers:
          - url: http://192.168.1.51:8090/
        serversTransport: pihole-dashboard-transport
    pihole2-dashboard:
      loadBalancer:
        servers:
          - url: http://192.168.1.52:8090/
        serversTransport: pihole-dashboard-transport
    pihole3-dashboard:
      loadBalancer:
        servers:
          - url: http://192.168.1.53:8090/
        serversTransport: pihole-dashboard-transport

  serversTransports:
    pihole-dashboard-transport:
      insecureSkipVerify: true
