http:

  routers:
    synology:
      entryPoints:
        - web-secure
      rule: Host(`synology.lab.omglolwtfbbq.com`)
      service: synology
      tls:
        certResolver: primary
        domains:
          - main: '*.lab.omglolwtfbbq.com'

  services:
    synology:
      loadBalancer:
        servers:
          - url: http://192.168.40.90:5000/
        serversTransport: synology-transport

  serversTransports:
    synology-transport:
      insecureSkipVerify: true
