version: '3.8'

services:

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    command:
      - '--path.rootfs=/host'
    volumes:
      - '/:/host:ro,rslave'
    cap_add:
      - SYS_TIME
    deploy:
      mode: global
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=9100
