version: '3.8'

services:

  valkey:
    image: valkey/valkey:8.0.2-alpine
    command: valkey-server --save 60 1 --loglevel warning
    volumes:
      - valkey-data:/data
    healthcheck:
      test: valkey-cli ping || exit 1
    deploy:
      placement:
        constraints:
          - node.role == manager # for mapped data volume

  valkey-exporter:
    image: oliver006/redis_exporter:v1.67.0
    environment:
      - REDIS_ADDR=redis://valkey:6379
    deploy:
      placement:
        constraints:
          - node.platform.arch == aarch64
      labels:
        - prometheus.swarm.enable=true
        - prometheus.swarm.port=9121

volumes:
  valkey-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/apps/valkey/data"
