version: '3.8'

services:

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'
    cap_add:
      - SYS_TIME
    # node_exporter must be on host network because reasons
    # can't join cluster network, so prometheus will need to scrape host:9100
    network_mode: host
    labels:
      - traefik.enable=false

networks:
  pi-cluster:
    external: true
