version: '3.8'

services:

  postgres:
    image: postgres:16.3-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - postgres-su-password
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-su-password
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    deploy:
      placement:
        constraints:
          - node.role == manager # for mapped data volume
          - node.platform.arch == x86_64
      labels:
        - prometheus.swarm.enable=false
        - traefik.enable=false

  # TODO phpMyAdmin / adminer

secrets:
  postgres-su-password:
    file: ./.secret.postgres-su-password

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/apps/postgres/data"
