version: '3.8'

services:

  visualizer:
    image: alexellis2/visualizer-arm:0.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.visualizer.rule=Host(`visualizer.lab.omglolwtfbbq.com`)
        - traefik.http.routers.visualizer.entrypoints=web-secure
        - traefik.http.routers.visualizer.tls.certResolver=primary
        - traefik.http.routers.visualizer.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.visualizer.loadbalancer.server.port=8080
