version: '3.8'

services:

  visualizer:
    image: dockersamples/visualizer@sha256:530c863672e7830d7560483df66beb4cbbcd375a9f3ec174ff5376616686a619
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.platform.arch == x86_64 # only because manager node req
      labels:
        - traefik.enable=true
        - traefik.http.routers.visualizer.rule=Host(`visualizer.lab.omglolwtfbbq.com`)
        - traefik.http.routers.visualizer.entrypoints=web-secure
        - traefik.http.routers.visualizer.tls.certResolver=primary
        - traefik.http.routers.visualizer.tls.domains[0].main=*.lab.omglolwtfbbq.com
        - traefik.http.services.visualizer.loadbalancer.server.port=8080
