version: '3.8'

services:

  valkey:
    image: valkey/valkey:7.2.5-alpine
    command: valkey-server --save 60 1 --loglevel warning
    volumes:
      - valkey-data:/data
    healthcheck:
      test: valkey-cli ping || exit 1
    deploy:
      placement:
        constraints:
          - node.role == manager # for mapped data volume

volumes:
  valkey-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/apps/valkey/data"
