version: '3.8'

services:

  redis:
    image: redis:7.2.5-alpine
    command: --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    healthcheck:
      test: redis-cli ping || exit 1
    deploy:
      placement:
        constraints:
          - node.platform.arch == x86_64

volumes:
  redis-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/opt/apps/redis"
